// <auto-generated/>
using System.Windows.Forms;

namespace RADB
{
    public partial class MainContentController
    {
        private MainContentForm Page
        {
            get { return Session.MainContentForm; }
            set { Session.MainContentForm = value; }
        }

        private FlatPanelA ContentLPanel { get { return Page.ContentLPanel; } }

        private FlatPanelA ContentRPanel { get { return Page.ContentRPanel; } }

        private FlatPanelA ContentRInsidePanel { get { return Page.ContentRInsidePanel; } }

        private FlatButtonA ConfigTabButton { get { return Page.ConfigTabButton; } }

        private FlatButtonA SpeedRunTabButton { get { return Page.SpeedRunTabButton; } }
    }

    public partial class SpeedRunController
    {
        private SpeedRunForm Page
        {
            get { return Session.SpeedRunForm; }
            set { Session.SpeedRunForm = value; }
        }

        private FlatTextBoxA SearchGameTextBox { get { return Page.SearchGameTextBox; } }

        private FlatButtonA SearchGameButton { get { return Page.SearchGameButton; } }

        private FlatDataGridA SearchGameGrid { get { return Page.SearchGameGrid; } }
    }

    public partial class MainCommon
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //Main
        private static FlatTabControlA tabMain { get { return Page.tabMain; } }
        //private static TabPage tabConsoles { get { return Page.tabConsoles; } }
        //private static TabPage tabGames { get { return Page.tabGames; } }
        //private static TabPage tabGameInfo { get { return Page.tabGameInfo; } }
        //private static TabPage tabGamesToPlay { get { return Page.tabGamesToPlay; } }
        //private static TabPage tabGamesToHide { get { return Page.tabGamesToHide; } }
        //private static TabPage tabUserInfo { get { return Page.tabUserInfo; } }
        //private static Label lblOutput { get { return Page.lblOutput; } }
    }

    public partial class MainConsole
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //Consoles
        private static Panel pnlDownloadConsoles { get { return Page.pnlDownloadConsoles; } }
        
        private static FlatButtonA UpdateConsolesButton { get { return Page.btnUpdateConsoles; } }
        
        private static FlatLabelA lblUpdateConsoles { get { return Page.lblUpdateConsoles; } }
        
        private static FlatLabelA lblProgressConsoles { get { return Page.lblProgressConsoles; } }
        
        private static FlatProgressBarA pgbConsoles { get { return Page.pgbConsoles; } }

        private static FlatDataGridA ConsolesDataGridView { get { return Page.dgvConsoles; } }
        
        private static ContextMenuStrip mnuConsoles { get { return Page.mnuConsoles; } }
        
        private static ToolStripMenuItem MergeGamesIconMenuItem { get { return Page.mniMergeGamesIcon; } }
        
        private static ToolStripMenuItem MergeGamesIconBadSizeMenuItem { get { return Page.mniMergeGamesIconBadSize; } }

        private static FlatLabelA lblNotFoundConsoles { get { return Page.lblNotFoundConsoles; } }
        
        private static FlatPictureBoxA picLoaderConsole { get { return Page.picLoaderConsole; } }
    }

    public partial class MainGame
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //Games
        private static Panel pnlDownloadGameList { get { return Page.pnlDownloadGameList; } }
        
        private static FlatButtonA btnUpdateGameList { get { return Page.btnUpdateGameList; } }
        
        private static FlatLabelA lblUpdateGameList { get { return Page.lblUpdateGameList; } }
        
        private static FlatLabelA lblProgressGameList { get { return Page.lblProgressGameList; } }
        
        private static FlatProgressBarA pgbGameList { get { return Page.pgbGameList; } }

        private static FlatPanelA pnlGamesConsoleName { get { return Page.pnlGamesConsoleName; } }
        
        private static FlatLabelB lblConsoleName { get { return Page.lblConsoleName; } }
        
        private static FlatLabelB lblConsoleGamesTotal { get { return Page.lblConsoleGamesTotal; } }

        private static FlatTextBoxA txtSearchGames { get { return Page.txtSearchGames; } }
        
        private static FlatButtonA btnGameFilters { get { return Page.btnGameFilters; } }
        
        private static FlatPanelA pnlFilters { get { return Page.pnlFilters; } }

        private static FlatCheckBoxA chkWithoutAchievements { get { return Page.chkWithoutAchievements; } }
        
        private static FlatCheckBoxA chkOfficial { get { return Page.chkOfficial; } }
        
        private static FlatCheckBoxA chkPrototype { get { return Page.chkPrototype; } }
        
        private static FlatCheckBoxA chkUnlicensed { get { return Page.chkUnlicensed; } }
        
        private static FlatCheckBoxA chkDemo { get { return Page.chkDemo; } }
        
        private static FlatCheckBoxA chkHack { get { return Page.chkHack; } }
        
        private static FlatCheckBoxA chkHomebrew { get { return Page.chkHomebrew; } }
        
        private static FlatCheckBoxA chkSubset { get { return Page.chkSubset; } }
        
        private static FlatCheckBoxA chkTestKit { get { return Page.chkTestKit; } }
        
        private static FlatCheckBoxA chkDemoted { get { return Page.chkDemoted; } }

        private static FlatLabelA lblNotFoundGameList { get { return Page.lblNotFoundGameList; } }
        
        private static FlatPictureBoxA picLoaderGameList { get { return Page.picLoaderGameList; } }

        private static FlatDataGridA dgvGames { get { return Page.dgvGames; } }
        
        private static ContextMenuStrip mnuGames { get { return Page.mnuGames; } }
        
        private static ToolStripMenuItem mniPlayGame { get { return Page.mniPlayGame; } }
        
        private static ToolStripMenuItem mniHideGame { get { return Page.mniHideGame; } }
        
        private static ToolStripMenuItem mniMergeGameBadges { get { return Page.mniMergeGameBadges; } }
    }

    public partial class MainGameInfo
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //GameInfo
        private static FlatButtonA btnUpdateInfo { get { return Page.btnUpdateInfo; } }
        
        private static FlatLabelA lblProgressInfo { get { return Page.lblProgressInfo; } }
        
        private static FlatProgressBarA pgbInfo { get { return Page.pgbInfo; } }
        
        private static FlatLabelA lblUpdateInfo { get { return Page.lblUpdateInfo; } }
        
        private static FlatPanelA pnlInfoScroll { get { return Page.pnlInfoScroll; } }

        private static FlatButtonA btnGamePage { get { return Page.btnGamePage; } }
        
        private static FlatButtonA btnHashes { get { return Page.btnHashes; } }
        
        private static FlatDataGridA dgvAchievements { get { return Page.dgvAchievements; } }

        private static FlatLabelA lblInfoName { get { return Page.lblInfoName; } }
        
        private static FlatPictureBoxA picInfoIcon { get { return Page.picInfoIcon; } }
        
        private static FlatLabelA lblInfoAchievements { get { return Page.lblInfoAchievements; } }

        private static FlatLabelA lblInfoDeveloper1 { get { return Page.lblInfoDeveloper1; } }
        
        private static FlatLabelA lblInfoPublisher1 { get { return Page.lblInfoPublisher1; } }
        
        private static FlatLabelA lblInfoGenre1 { get { return Page.lblInfoGenre1; } }
        
        private static FlatLabelA lblInfoReleased1 { get { return Page.lblInfoReleased1; } }

        private static FlatPictureBoxA picInfoTitle { get { return Page.picInfoTitle; } }
        
        private static FlatPictureBoxA picInfoInGame { get { return Page.picInfoInGame; } }
        
        private static FlatPictureBoxA picInfoBoxArt { get { return Page.picInfoBoxArt; } }

        private static FlatPanelA pnlInfoImages { get { return Page.pnlInfoImages; } }
        
        private static FlatPanelA pnlInfoTitle { get { return Page.pnlInfoTitle; } }
        
        private static FlatPanelA pnlInfoInGame { get { return Page.pnlInfoInGame; } }
        
        private static FlatPanelA pnlInfoBoxArt { get { return Page.pnlInfoBoxArt; } }
        
        private static FlatGroupBoxA gpbInfo { get { return Page.gpbInfo; } }
        
        private static FlatGroupBoxA gpbInfoAchievements { get { return Page.gpbInfoAchievements; } }
        
        private static FlatTextBoxA txtSearchAchiev { get { return Page.txtSearchAchiev; } }
    }

    public partial class MainGameToPlay
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //GameToPlay
        private static FlatDataGridA dgvGamesToPlay { get { return Page.dgvGamesToPlay; } }
        
        private static ContextMenuStrip mnuGamesToPlay { get { return Page.mnuGamesToPlay; } }
        
        private static ToolStripMenuItem mniRemoveGameToPlay { get { return Page.mniRemoveGameToPlay; } }
        
        private static FlatLabelA lblNotFoundGamesToPlay { get { return Page.lblNotFoundGamesToPlay; } }
    }

    public partial class MainGameToHide
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //GameToHide
        private static FlatDataGridA dgvGamesToHide { get { return Page.dgvGamesToHide; } }
        
        private static ContextMenuStrip mnuGamesToHide { get { return Page.mnuGamesToHide; } }
        
        private static ToolStripMenuItem mniRemoveGameToHide { get { return Page.mniRemoveGameToHide; } }
        
        private static FlatLabelA lblNotFoundGamesToHide { get { return Page.lblNotFoundGamesToHide; } }
    }

    public partial class MainUserInfo
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        //UserInfo
        private static FlatTextBoxA txtUsername { get { return Page.txtUsername; } }
        
        private static FlatButtonA btnGetUserInfo { get { return Page.btnGetUserInfo; } }
        
        private static FlatButtonA btnUserPage { get { return Page.btnUserPage; } }
        
        private static LinkLabel lnkUserRank { get { return Page.lnkUserRank; } }

        private static FlatListViewA lsvGameAwards { get { return Page.lsvGameAwards; } }
        
        private static FlatLabelA lblUserCompletion { get { return Page.lblUserCompletion; } }
        
        private static FlatPictureBoxA picUserLastGame { get { return Page.picUserLastGame; } }
        
        private static FlatPictureBoxA picLoaderUserAwards { get { return Page.picLoaderUserAwards; } }

        private static FlatLabelA lblUserStatus { get { return Page.lblUserStatus; } }
        
        private static FlatLabelA lblUserName { get { return Page.lblUserName; } }
        
        private static FlatLabelA lblUserMotto { get { return Page.lblUserMotto; } }

        private static FlatLabelA lblUserMemberSince { get { return Page.lblUserMemberSince; } }
        
        private static FlatLabelA lblUserLastActivity { get { return Page.lblUserLastActivity; } }
        
        private static FlatLabelA lblUserAccountType { get { return Page.lblUserAccountType; } }

        private static FlatLabelA lblUserHCPoints { get { return Page.lblUserHCPoints; } }
        
        private static FlatLabelA lblUserRetroRatio { get { return Page.lblUserRetroRatio; } }
        
        private static FlatLabelA lblUserSoftPoints { get { return Page.lblUserSoftPoints; } }
        
        private static FlatLabelA lblUserSoftRank { get { return Page.lblUserSoftRank; } }

        private static FlatPictureBoxA picUserName { get { return Page.picUserName; } }
        
        private static FlatLabelA lblUserRichPresence { get { return Page.lblUserRichPresence; } }
        
        private static FlatLabelA lblUserLastConsole { get { return Page.lblUserLastConsole; } }
        
        private static FlatLabelA lblUserLastGame { get { return Page.lblUserLastGame; } }

        private static FlatPanelA pnlAwardFloating { get { return Page.pnlAwardFloating; } }
        
        private static FlatPictureBoxA picAwardFloating { get { return Page.picAwardFloating; } }
        
        private static FlatLabelA lblAwardFloatingTitle { get { return Page.lblAwardFloatingTitle; } }
        
        private static FlatLabelA lblAwardFloatingDesc { get { return Page.lblAwardFloatingDesc; } }
    }

    public partial class MainAbout
    {
        private static Main Page { get { return Session.MainFormRA; } }
        
        private static FlatButtonA RALoginButton { get { return Page.btnRALogin; } }
        
        private static FlatLabelA lblRALogin { get { return Page.lblSystemReLogin; } }
        
        private static FlatButtonA RAProfileButton { get { return Page.btnRAProfileAbout; } }

        private static FlatPictureBoxA picUserCheevos { get { return Page.picUserCheevos; } }
        
        private static FlatLabelA lblUserCheevos { get { return Page.lblUserCheevos; } }
        
        private static FlatButtonA UserCheevosButton { get { return Page.btnUserCheevos; } }
        
        private static Label lblCheevoLoopUpdate { get { return Page.lblCheevoLoopUpdate; } }
        
        private static CheckBox chkUserCheevos { get { return Page.chkUserCheevos; } }

        private static FlatCheckBoxA chkDarkMode { get { return Page.chkDarkMode; } }
        
        private static FlatCheckBoxA chkDebugMode { get { return Page.chkDebugMode; } }
    }
}