//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM Console 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (Name LIKE &apos;%&apos;+@Name+&apos;%&apos; 
        ///		OR (@Name = &apos;&apos; OR @Name IS NULL)) 
        ///;
        ///--.
        /// </summary>
        internal static string ConsoleExcluir {
            get {
                return ResourceManager.GetString("ConsoleExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO Console ( 
        ///	  ID 
        ///	, Name 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Name 
        ///);
        ///--.
        /// </summary>
        internal static string ConsoleIncluir {
            get {
                return ResourceManager.GetString("ConsoleIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  ID 
        ///	, Name 
        ///FROM Console 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (Name LIKE &apos;%&apos;+@Name+&apos;%&apos; 
        ///		OR (@Name = &apos;&apos; OR @Name IS NULL)) 
        ///	.
        /// </summary>
        internal static string ConsoleListar {
            get {
                return ResourceManager.GetString("ConsoleListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM game 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (ConsoleID = @ConsoleID 
        ///		OR (@ConsoleID = 0 OR @ConsoleID IS NULL)) 
        ///;
        ///--.
        /// </summary>
        internal static string GameExcluir {
            get {
                return ResourceManager.GetString("GameExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO game ( 
        ///	  ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, NumAchievements 
        ///	, NumLeaderboards 
        ///	, Points 
        ///	, ImageIcon
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Title 
        ///	, @ConsoleID 
        ///	, @NumAchievements 
        ///	, @NumLeaderboards 
        ///	, @Points 
        ///	, @ImageIcon 
        ///);
        ///--.
        /// </summary>
        internal static string GameIncluir {
            get {
                return ResourceManager.GetString("GameIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT
        ///	  ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, NumAchievements 
        ///	, NumLeaderboards 
        ///	, Points 
        ///	, ImageIcon 
        ///FROM game  
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (Title LIKE &apos;%&apos;+@Title+&apos;%&apos; 
        ///		OR (@Title = &apos;&apos; OR @Title IS NULL)) 
        ///	AND (ConsoleID = @ConsoleID 
        ///		OR (@ConsoleID = 0 OR @ConsoleID IS NULL)) 
        ///	.
        /// </summary>
        internal static string GameListar {
            get {
                return ResourceManager.GetString("GameListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jpegoptim_1_4_7 {
            get {
                object obj = ResourceManager.GetObject("jpegoptim_1_4_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pngcrush_1_8_11_w64 {
            get {
                object obj = ResourceManager.GetObject("pngcrush_1_8_11_w64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
