//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM Console 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID OR COALESCE(@ID, 0) = 0) 
        ///	AND (Name LIKE &apos;%&apos;+@Name+&apos;%&apos; OR COALESCE(@Name, &apos;&apos;) = &apos;&apos;) 
        ///;
        ///--.
        /// </summary>
        internal static string ConsoleDelete {
            get {
                return ResourceManager.GetString("ConsoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO Console ( 
        ///	  ID 
        ///	, Name 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Name 
        ///);
        ///--.
        /// </summary>
        internal static string ConsoleInsert {
            get {
                return ResourceManager.GetString("ConsoleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	 co.ID 
        ///	, c.Name AS Company 
        ///	,(CASE WHEN ci.ConsoleNameComplete IS NULL THEN 
        ///		CASE WHEN co.Name IS NULL THEN c.Name ELSE co.Name END 
        ///	  ELSE ci.ConsoleNameComplete END) AS CName 
        ///	, SUM(CASE WHEN g.NumAchievements &gt; 0 THEN 1 ELSE 0 END) NumGames 
        ///	, Count(g.ID) AS TotalGames 
        ///FROM Company AS c 
        ///	LEFT JOIN CompanyItems AS ci ON ci.CompanyID = c.ID 
        ///		--AND ci.Active = 1 
        ///	LEFT JOIN Console AS co ON co.ID = ci.ConsoleID 
        ///	LEFT JOIN GameData AS g ON (g.ConsoleID = co.ID OR co.Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleList {
            get {
                return ResourceManager.GetString("ConsoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fbidev {
            get {
                object obj = ResourceManager.GetObject("fbidev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM GameData 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID OR COALESCE(@ID, 0) = 0) 
        ///	AND (ConsoleID = @ConsoleID OR COALESCE(@ConsoleID, 0) = 0) 
        ///;
        ///--.
        /// </summary>
        internal static string GameDelete {
            get {
                return ResourceManager.GetString("GameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM GameToHide 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID OR COALESCE(@ID, 0) = 0) 
        ///;
        ///--.
        /// </summary>
        internal static string GameDeleteFromHide {
            get {
                return ResourceManager.GetString("GameDeleteFromHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM GameToPlay 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID OR COALESCE(@ID, 0) = 0) 
        ///;
        ///--.
        /// </summary>
        internal static string GameDeleteFromPlay {
            get {
                return ResourceManager.GetString("GameDeleteFromPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM GameDataExtend 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID OR COALESCE(@ID, 0) = 0) 
        ///	AND (ConsoleID = @ConsoleID OR COALESCE(@ConsoleID, 0) = 0) 
        ///;
        ///--.
        /// </summary>
        internal static string GameExtendDelete {
            get {
                return ResourceManager.GetString("GameExtendDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO GameDataExtend ( 
        ///	  ID 
        ///	, ConsoleID 
        ///	, Developer 
        ///	, Publisher 
        ///	, Genre 
        ///	, Released 
        ///	, ImageTitle 
        ///	, ImageIngame 
        ///	, ImageBoxArt 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @ConsoleID 
        ///	, @Developer 
        ///	, @Publisher 
        ///	, @Genre 
        ///	, @Released 
        ///	, @ImageTitle 
        ///	, @ImageIngame 
        ///	, @ImageBoxArt 
        ///);
        ///--.
        /// </summary>
        internal static string GameExtendInsert {
            get {
                return ResourceManager.GetString("GameExtendInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  g.ID 
        ///	, g.Title 
        ///	, g.ConsoleID 
        ///	, c.Name AS ConsoleName 
        ///	, g.ImageIcon 
        ///	, g.NumAchievements 
        ///	, g.Points 
        ///	, g.NumLeaderboards 
        ///	, g.DateModified 
        ///	, g.ForumTopicID 
        ///	, gx.Developer 
        ///	, gx.Publisher 
        ///	, gx.Genre 
        ///	, gx.Released 
        ///	, gx.ImageTitle 
        ///	, gx.ImageIngame 
        ///	, gx.ImageBoxArt 
        ///FROM GameDataExtend AS gx 
        ///	LEFT JOIN GameData AS g ON g.ID = gx.ID 
        ///	LEFT JOIN Console AS c ON c.ID = g.ConsoleID 
        ///WHERE 1 = 1 
        ///	AND (g.ID = @ID OR COALESCE(@ID, 0) = 0) 
        ///	AND (g.Cons [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameExtendList {
            get {
                return ResourceManager.GetString("GameExtendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO GameData ( 
        ///	  ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, ImageIcon 
        ///	, NumAchievements 
        ///	, Points 
        ///	, NumLeaderboards 
        ///	, DateModified 
        ///	, ForumTopicID 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Title 
        ///	, @ConsoleID 
        ///	, @ImageIcon 
        ///	, @NumAchievements 
        ///	, @Points 
        ///	, @NumLeaderboards 
        ///	, @DateModified 
        ///	, @ForumTopicID 
        ///);
        ///--.
        /// </summary>
        internal static string GameInsert {
            get {
                return ResourceManager.GetString("GameInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO GameToHide ( 
        ///	  ID 
        ///	) VALUES ( 
        ///	  @ID 
        ///);
        ///--.
        /// </summary>
        internal static string GameInsertToHide {
            get {
                return ResourceManager.GetString("GameInsertToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO GameToPlay ( 
        ///	  ID 
        ///	) VALUES ( 
        ///	  @ID 
        ///);
        ///--.
        /// </summary>
        internal static string GameInsertToPlay {
            get {
                return ResourceManager.GetString("GameInsertToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT
        ///	  g.ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, c.Name AS ConsoleName 
        ///	, ImageIcon 
        ///	, NumAchievements 
        ///	, Points 
        ///	, NumLeaderboards 
        ///	, DateModified 
        ///	, ForumTopicID 
        ///FROM GameData AS g 
        ///	INNER JOIN Console AS c ON c.ID = g.ConsoleID 
        ///WHERE 1 = 1 
        ///	AND g.ID != (CASE WHEN @allTables = 1 THEN (SELECT -1) ELSE COALESCE((SELECT ID FROM GameToPlay AS p WHERE p.ID = g.ID), -1) END) 
        ///	AND g.ID != (CASE WHEN @allTables = 1 THEN (SELECT -1) ELSE COALESCE((SELECT ID FROM GameToHide AS h WHERE h.ID =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT
        ///	  g.ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, c.Name AS ConsoleName 
        ///	, ImageIcon 
        ///	, NumAchievements 
        ///	, Points 
        ///	, NumLeaderboards 
        ///	, DateModified 
        ///	, ForumTopicID 
        ///FROM GameData AS g 
        ///	INNER JOIN Console AS c ON c.ID = g.ConsoleID 
        ///	INNER JOIN GameToHide AS gh ON gh.ID = g.ID 
        ///WHERE 1 = 1 
        ///	.
        /// </summary>
        internal static string GameListToHide {
            get {
                return ResourceManager.GetString("GameListToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT
        ///	  g.ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, c.Name AS ConsoleName 
        ///	, ImageIcon 
        ///	, NumAchievements 
        ///	, Points 
        ///	, NumLeaderboards 
        ///	, DateModified 
        ///	, ForumTopicID 
        ///FROM GameData AS g 
        ///	INNER JOIN Console AS c ON c.ID = g.ConsoleID 
        ///	INNER JOIN GameToPlay AS gh ON gh.ID = g.ID 
        ///WHERE 1 = 1 
        ///	.
        /// </summary>
        internal static string GameListToPlay {
            get {
                return ResourceManager.GetString("GameListToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconForm {
            get {
                object obj = ResourceManager.GetObject("iconForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jpegoptim_1_4_7 {
            get {
                object obj = ResourceManager.GetObject("jpegoptim_1_4_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jpegoptim_1_5_0 {
            get {
                object obj = ResourceManager.GetObject("jpegoptim_1_5_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notfound {
            get {
                object obj = ResourceManager.GetObject("notfound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pngcrush_1_8_11_w64 {
            get {
                object obj = ResourceManager.GetObject("pngcrush_1_8_11_w64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pngcrush_1_8_13_w64 {
            get {
                object obj = ResourceManager.GetObject("pngcrush_1_8_13_w64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
