//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM Console 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (Name LIKE &apos;%&apos;+@Name+&apos;%&apos; 
        ///		OR (@Name = &apos;&apos; OR @Name IS NULL)) 
        ///;
        ///--.
        /// </summary>
        internal static string ConsoleExcluir {
            get {
                return ResourceManager.GetString("ConsoleExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO Console ( 
        ///	  ID 
        ///	, Name 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Name 
        ///);
        ///--.
        /// </summary>
        internal static string ConsoleIncluir {
            get {
                return ResourceManager.GetString("ConsoleIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	 co.ID 
        ///	, c.Name AS Company 
        ///	,(CASE WHEN ci.ConsoleNameComplete IS NULL THEN co.Name ELSE ci.ConsoleNameComplete END) AS Name 
        ///	, SUM(CASE WHEN g.NumAchievements &gt; 0 THEN 1 ELSE 0 END) NumGames 
        ///	, Count(g.ID) AS TotalGames 
        ///FROM Company AS c 
        ///	LEFT JOIN CompanyItems AS ci ON ci.CompanyID = c.ID 
        ///		--AND ci.Active = 1 
        ///	LEFT JOIN Console AS co ON co.ID = ci.ConsoleID 
        ///	LEFT JOIN GameData AS g on g.ConsoleID = co.ID OR co.Name IS NULL 
        ///WHERE 1 = 1 
        ///	AND co.Name IS NULL AND @ID = 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleListar {
            get {
                return ResourceManager.GetString("ConsoleListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM GameData 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (ConsoleID = @ConsoleID 
        ///		OR (@ConsoleID = 0 OR @ConsoleID IS NULL)) 
        ///;
        ///--.
        /// </summary>
        internal static string GameExcluir {
            get {
                return ResourceManager.GetString("GameExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///DELETE 
        ///FROM GameDataExtend 
        ///WHERE 1 = 1 
        ///	AND (ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (ConsoleID = @ConsoleID 
        ///		OR (@ConsoleID = 0 OR @ConsoleID IS NULL)) 
        ///;
        ///--.
        /// </summary>
        internal static string GameExtendExcluir {
            get {
                return ResourceManager.GetString("GameExtendExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO GameDataExtend ( 
        ///	  ID
        ///	, Developer 
        ///	, Publisher 
        ///	, Genre 
        ///	, Released 
        ///	, ImageTitle 
        ///	, ImageIngame 
        ///	, ImageBoxArt 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Developer 
        ///	, @Publisher 
        ///	, @Genre 
        ///	, @Released 
        ///	, @ImageTitle 
        ///	, @ImageIngame 
        ///	, @ImageBoxArt 
        ///);
        ///--.
        /// </summary>
        internal static string GameExtendIncluir {
            get {
                return ResourceManager.GetString("GameExtendIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  g.ID 
        ///	, g.Title 
        ///	, g.ConsoleID 
        ///	, c.Name as ConsoleName 
        ///	, g.ImageIcon
        ///	, g.NumAchievements 
        ///	, g.Points 
        ///	, g.NumLeaderboards 
        ///	, g.DateModified 
        ///	, g.ForumTopicID 
        ///	, gx.Developer 
        ///	, gx.Publisher 
        ///	, gx.Genre 
        ///	, gx.Released 
        ///	, gx.ImageTitle 
        ///	, gx.ImageIngame 
        ///	, gx.ImageBoxArt 
        ///FROM GameDataExtend AS gx 
        ///	LEFT JOIN GameData AS g ON g.ID = gx.ID 
        ///	LEFT JOIN Console AS c ON c.ID = g.ConsoleID 
        ///WHERE 1 = 1 
        ///	AND (g.ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameExtendListar {
            get {
                return ResourceManager.GetString("GameExtendListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///INSERT INTO GameData ( 
        ///	  ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, ImageIcon 
        ///	, NumAchievements 
        ///	, Points 
        ///	, NumLeaderboards 
        ///	, DateModified 
        ///	, ForumTopicID 
        ///	) VALUES ( 
        ///	  @ID 
        ///	, @Title 
        ///	, @ConsoleID 
        ///	, @ImageIcon 
        ///	, @NumAchievements 
        ///	, @Points 
        ///	, @NumLeaderboards 
        ///	, @DateModified 
        ///	, @ForumTopicID 
        ///);
        ///--.
        /// </summary>
        internal static string GameIncluir {
            get {
                return ResourceManager.GetString("GameIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT
        ///	  G.ID 
        ///	, Title 
        ///	, ConsoleID 
        ///	, C.Name as ConsoleName 
        ///	, ImageIcon 
        ///	, NumAchievements 
        ///	, Points 
        ///	, NumLeaderboards 
        ///	, DateModified 
        ///	, ForumTopicID 
        ///FROM GameData AS G 
        ///	LEFT JOIN Console as C on C.ID=G.ConsoleID 
        ///WHERE 1 = 1 
        ///	AND (G.ID = @ID 
        ///		OR (@ID = 0 OR @ID IS NULL)) 
        ///	AND (G.Title LIKE &apos;%&apos;+@Title+&apos;%&apos; 
        ///		OR (@Title = &apos;&apos; OR @Title IS NULL)) 
        ///	AND (G.ConsoleID = @ConsoleID 
        ///		OR (@ConsoleID = 0 OR @ConsoleID IS NULL)) 
        ///	.
        /// </summary>
        internal static string GameListar {
            get {
                return ResourceManager.GetString("GameListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jpegoptim_1_4_7 {
            get {
                object obj = ResourceManager.GetObject("jpegoptim_1_4_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notfound {
            get {
                object obj = ResourceManager.GetObject("notfound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pngcrush_1_8_11_w64 {
            get {
                object obj = ResourceManager.GetObject("pngcrush_1_8_11_w64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
